version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
volumes:
  pgdata: {}